#!/bin/bash
if [[ -L "${BASH_SOURCE[0]}" ]]; then
	DIR="$( cd "$( dirname $(readlink "${BASH_SOURCE[0]}") )" && pwd )"
else
	DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

if [ `uname` = Linux ]; then
	JCROOT=$DIR
	java -classpath "$JCROOT/out/production/jconductor:$JCROOT/lib/*"  -Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR com.netbric.s5.cli.CliMain $*
else
	JCROOT=. 
	java -classpath "$JCROOT/out/production/jconductor;$JCROOT/lib/*"  -Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR com.netbric.s5.cli.CliMain $*
fi
