#!/bin/bash

if [ `uname` = Linux ]; then
	JCROOT=/root/v2/jconductor
	java -classpath "$JCROOT/out/production/jconductor:$JCROOT/lib/*"  -Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR com.netbric.s5.cli.CliMain $*
else
	JCROOT=. 
	java -classpath "$JCROOT/out/production/jconductor;$JCROOT/lib/*"  -Dorg.slf4j.simpleLogger.defaultLogLevel=ERROR com.netbric.s5.cli.CliMain $*
fi
